---
# Bugs as of this writing:
#   include_role does not work with looping, so have to specify each as an individual task
#   sometimes software installations will get notified as changed even if they do not change

# Steps to run as root
- hosts: joey_laptop
  become: yes

  vars:
    user_name: joey

  tasks:
  - name: "Change hostname"
    hostname:
      name: "{{ host_name }}"

  - name: "Change time zone"
    timezone:
      name: "{{ time_zone }}"

  - name: "Create publicly accessible folders"
    file:
      path: "/{{ folder_name }}"
      owner: root
      group: root
      mode: 0777
      state: directory
    with_items:
      - data
      - tmp2
      - work
    loop_control:
      loop_var: folder_name

  - name: "Install console software"
    include_role:
      name: software_packs
    vars:
      software_pack_list: common_console_tools

  - name: "Install KDE applications"
    include_role:
      name: software_packs
    vars:
      software_pack_list: kde_tools

  - name: "Install other applications"
    include_role:
      name: software_packs
    vars:
      software_pack_list: other

  - name: "Install LibreOffice"
    include_role:
      name: libreoffice

  - name: "Install KeePassXC"
    include_role:
      name: keepassxc

  - name: "Install Etcher"
    include_role:
      name: etcher

  - name: "Install VirtualBox"
    include_role:
      name: virtualbox
    vars:
      virtualbox_version: "5.2"
      virtualbox_user: "{{ user_name }}"

  - name: "Install Docker"
    include_role:
      name: docker
    vars:
      docker_user: "{{ user_name }}"
      docker_enabled: False




# Steps to run as user
- hosts: joey_laptop

  tasks:
  - name: "Setup bash aliases"
    include_role:
      name: bash_aliases

  - name: "Setup nano"
    include_role:
      name: nano

  - name: "Create home bin folder"
    file:
      path: "/home/{{ ansible_user_id }}/bin"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: 0755
      state: directory

  - name: "Set up git"
    include_role:
      name: git
