---
# PLAYBOOK

- hosts: joey_leap_42_3_desktop
  become: yes

  tasks:
  - name: "Change hostname"
    hostname:
      name: "{{ host_name }}"

  - name: "Change time zone"
    timezone:
      name: "{{ time_zone }}"

  - name: "Create publicly accessible folders"
    file:
      path: "{{ item }}"
      owner: root
      group: root
      mode: 0777
      state: directory
    with_items:
      - "/data"
      - "/tmp2"

  - name: "Add Packman repository"
    zypper_repository:
      name: "Packman Repository"
      description: "Leap 42.3 Packman Repository"
      repo: "http://packman.inode.at/suse/openSUSE_Leap_42.3/"
      state: present
      auto_import_keys: yes
      runrefresh: yes

  - name: "Install software"
    include_role:
      name: software_packs
    vars:
      software_pack_type: "{{ item }}"
    with_items:
      - common_console_tools
      - common_gui_tools
      - graphics_tools


# - hosts: joey_leap_42_3_desktop

# TODO:
#   install dotfiles
#   configure git
#   configure firewall
#   nano color highlighting

