---
# Steps to run as root
- hosts: joey_laptop
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: "Change hostname"
    hostname:
      name: "{{ host_name }}"

  - name: "Change time zone"
    timezone:
      name: "{{ time_zone }}"

  - name: "Create publicly accessible folders"
    file:
      path: "/{{ folder_name }}"
      owner: root
      group: root
      mode: 0777
      state: directory
    with_items:
      - "data"
      - "tmp2"
    loop_control:
      loop_var: folder_name

  - name: "Install console software"
    include_role:
      name: software_packs
    vars:
      software_pack_list: "common_console_tools"

  - name: "Install KDE applications"
    include_role:
      name: software_packs
    vars:
      software_pack_list: "kde_tools"

  - name: "Install computer-specific applications"
    package:
      name:
        - "pinta"
        - "dosbox"
        - "ffmpeg"
        - "vlc"
      state: present


# Steps to run as user
# - hosts: joey_laptop

#   tasks:
