---
################################################################################
# Root playbook to set up main admin user, run as root user
# Once this playbook is done, you should run all future playbooks
#   as the admin user.
################################################################################

# ansible-playbook vps_webserver_initial.yml --inventory=./hosts --ask-pass -v

- hosts: vps_webserver
  vars:
    ansible_user: root
    local_source_user: ansibleuser

  vars_prompt:
  - name: "admin_password"
    prompt: "Enter password for admin user"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes

  tasks:
  - name: "Add sshusers group"
    group:
      name: sshusers
      state: present

  - name: "Add main admin user: {{ admin_user }}"
    user:
      name: "{{ admin_user }}"
      shell: /bin/bash
      comment: "{{ admin_full_name }}"
      groups:
        - sudo
        - sshusers
      password: "{{ admin_password }}"
      update_password: on_create
      state: present

  - name: "Add authorized key for login for user: {{ admin_user }}"
    authorized_key:
      user: "{{ admin_user }}"
      state: present
      key: "{{ lookup('file', '/home/{{ local_source_user }}/.ssh/id_rsa.pub') }}"
    become: yes
    become_user: "{{ admin_user }}"

  - name: "Lock down ssh to users in group sshusers"
    include_role:
      name: ssh
      tasks_from: "lock_down_ssh.yml"
