---
################################################################################
# Playbook to lock down admin user, run as this user
################################################################################
- hosts: vps_webserver

  tasks:
  - name: "Add authorized key for login for user: {{ ansible_user }}"
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/id_rsa.pub') }}"

  - name: "Lock down ssh to users in group sshusers"
    include_role:
      name: ssh
      tasks_from: "lock_down_ssh.yml"
