---
# TODO: lock down ssh, turn on firewall

################################################################################
# Root playbook to set up main admin user, run as root
################################################################################
- hosts: vps_webserver
  vars:
    ansible_user: root
    admin_user: joey
    admin_full_name: "Joey Rockhold"
  vars_prompt:
  - name: "admin_password"
    prompt: "Enter password for admin user"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes

  tasks:
  - name: "Add sshusers group"
    group:
      name: sshusers
      state: present

  - name: "Add main admin user: {{ admin_user }}"
    user:
      name: "{{ admin_user }}"
      shell: /bin/bash
      comment: "{{ admin_full_name }}"
      groups:
        - sudo
        - sshusers
      password: "{{ admin_password }}"
      update_password: on_create
      state: present
