---
# tasks file for all_computers

- name: "Change hostname"
  hostname:
    name: "{{ host_name }}"

- name: "Change time zone"
  timezone:
    name: "{{ time_zone }}"

- name: "Create publicly accessible folders"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0777
    state: directory
  with_items: "{{ all_computers_public_folders }}"
