---
# tasks file for creating a swap file.

# Required parameters: swap_file_size_mb
# Defaulted parameters: swap_file_dir, swap_file_name

- name: "Set fact for whether swap_file steps should continue"
  set_fact:
    swap_file_continue: True
  changed_when: False

- name: "Check if swap file already exists and is active"
  shell: cat /proc/swaps|grep "{{ swap_file_dir }}/{{ swap_file_name }}"|wc -l
  register: swap_file_active
  changed_when: False

- name: "Stop processing if swap file already exists and is active"
  set_fact:
    swap_file_continue: False
  changed_when: False
  when: not swap_file_active.stdout == "0"

- name: "Create swap folder"
  file:
    path: "{{ swap_file_dir }}"
    owner: root
    group: root
    mode: 0700
    state: directory
    follow: yes
  become: yes
  when: swap_file_continue

- name: "Touch swap file"
  file:
    path: "{{ swap_file_dir }}/{{ swap_file_name }}"
    owner: root
    group: root
    mode: 0600
    state: touch
    follow: yes
  become: yes
  when: swap_file_continue

- name: "Build swap file space"
  shell: dd if=/dev/zero of="{{ swap_file_dir }}/{{ swap_file_name }}" bs=1048576 count="{{ swap_file_size_mb }}"
  become: yes
  when: swap_file_continue

- name: "Convert file to swap file"
  shell: mkswap "{{ swap_file_dir }}/{{ swap_file_name }}"
  become: yes
  when: swap_file_continue

- name: "Turn on swap space"
  shell: swapon "{{ swap_file_dir }}/{{ swap_file_name }}"
  become: yes
  when: swap_file_continue

- name: "Put swap file in fstab"
  lineinfile:
    path: /etc/fstab
    create: no
    state: present
    regexp: "^{{ swap_file_dir }}/{{ swap_file_name }}"
    line: "{{ swap_file_dir }}/{{ swap_file_name }} none swap sw 0 0"
  become: yes
