---
# variables: docker_user, docker_enabled

- name: "Install Docker pre-requisites for Ubuntu"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: yes

- name: "Add Docker GPG key for Ubuntu"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: present
  become: yes

- name: "Add Docker repository for Ubuntu"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: "Install Docker for Ubuntu"
  apt:
    name: docker-ce
    state: present
  become: yes

- name: "Add docker group to user: {{ ansible_user }}"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: "Disable docker service for Ubuntu"
  systemd:
    enabled: no
    name: docker
    state: stopped
  when: not docker_enabled
  become: yes

- name: "Enable docker service for Ubuntu"
  systemd:
    enabled: yes
    name: docker
    state: started
  when: docker_enabled
  become: yes
