---
# tasks file for nano

- name: "Install nano"
  package:
    name: nano
    state: present
  become: yes

- name: "Create symlink to .nanorc"
  file:
    src: "{{ development_dir }}/dotfiles/nano/.nanorc"
    dest: "/home/{{ ansible_user }}/.nanorc"
    state: link
