---
- name: "Create ssh folder in home directory for user: {{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ user_group }}"
    mode: 0700

- name: "Copy ssh private key"
  copy:
    src: "/home/{{ local_source_user }}/.ssh/id_rsa"
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    owner: "{{ ansible_user }}"
    group: "{{ user_group }}"
    mode: 0600
    force: no

- name: "Copy ssh public key"
  copy:
    src: "/home/{{ local_source_user }}/.ssh/id_rsa.pub"
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
    owner: "{{ ansible_user }}"
    group: "{{ user_group }}"
    mode: 0644
    force: no
