---

- name: "Set ssh properties"
  lineinfile:
    path: "/etc/ssh/sshd_config"
    state: present
    regexp: "{{ item.line_start }}"
    line: "{{ item.line_change }}"
  with_items:
    - { line_start: "^PasswordAuthentication ", line_change: "PasswordAuthentication no" }
    - { line_start: "^PermitRootLogin ", line_change: "PermitRootLogin no" }
    - { line_start: "^AllowGroups ", line_change: "AllowGroups sshusers" }
  register: ssh_properties
  become: yes

- name: "Restart ssh service"
  systemd:
    name: "sshd.service"
    enabled: yes
    state: restarted
  when: ssh_properties.changed
  become: yes
