---
- name: "Add LibreOffice Fresh PPA for Ubuntu"
  apt_repository:
    repo: "ppa:libreoffice/ppa"
    state: present
  become: yes

- name: "Install LibreOffice Fresh for Ubuntu"
  apt:
    name: libreoffice
    state: present
  become: yes