---
# tasks file for creating a swap file.

# Required parameters: swapfile_size_mb
# Defaulted parameters: swapfile_dir, swapfile_name

- name: "Set fact for whether swapfile steps should continue"
  set_fact:
    swapfile_continue: True
  changed_when: False

- name: "Check if swap file already exists and is active"
  shell: cat /proc/swaps|grep "{{ swapfile_dir }}/{{ swapfile_name }}"|wc -l
  register: swapfile_active
  changed_when: False

- name: "Stop processing if swap file already exists and is active"
  set_fact:
    swapfile_continue: False
  changed_when: False
  when: not swapfile_active.stdout == "0"

- name: "Create swap folder"
  file:
    path: "{{ swapfile_dir }}"
    owner: root
    group: root
    mode: 0700
    state: directory
    follow: yes
  become: yes
  when: swapfile_continue

- name: "Touch swap file"
  file:
    path: "{{ swapfile_dir }}/{{ swapfile_name }}"
    owner: root
    group: root
    mode: 0600
    state: touch
    follow: yes
  become: yes
  when: swapfile_continue

- name: "Build swap file space"
  shell: dd if=/dev/zero of="{{ swapfile_dir }}/{{ swapfile_name }}" bs=1048576 count="{{ swapfile_size_mb }}"
  become: yes
  when: swapfile_continue

- name: "Convert file to swap file"
  shell: mkswap "{{ swapfile_dir }}/{{ swapfile_name }}"
  become: yes
  when: swapfile_continue

- name: "Turn on swap space"
  shell: swapon "{{ swapfile_dir }}/{{ swapfile_name }}"
  become: yes
  when: swapfile_continue

- name: "Put swap file in fstab"
  lineinfile:
    path: /etc/fstab
    create: no
    state: present
    regexp: "^{{ swapfile_dir }}/{{ swapfile_name }}"
    line: "{{ swapfile_dir }}/{{ swapfile_name }} none swap sw 0 0"
  become: yes
