---
################################################################################
# Playbook to setup VPS web server
################################################################################

# eval $(ssh-agent); ssh-add ~/.ssh/id_rsa
# ansible-playbook vps_webserver.yml --inventory=./hosts --ask-become-pass -v

- hosts: vps_webserver
  vars:
    console_tools:
      - aptitude
      - curl
      - git
      - htop
      - man
      - mc
      - nano
      - sqlite3
      - sshfs
      - tasksel
      - tmux
      - tree
      - wget
      # archive tools
      - p7zip
      - rar
      - unar
      - unrar
      - unzip
      - zip
      # Needed as an Ansible-managed machine
      - python3-pexpect

  tasks:

################################################################################
# Server Configuration
################################################################################
  - name: "Change hostname"
    hostname:
      name: "{{ host_name }}"
    become: yes

  - name: "Change time zone"
    timezone:
      name: "{{ time_zone }}"
    become: yes

  - name: "Import swap_file role"
    import_role:
      name: swap_file
    vars:
      swapfile_size_mb: "768"

# TODO: mount data drive
# TODO: user config files
# TODO: firewall

################################################################################
# Folders / Links Configuration
################################################################################
  - name: "Create publicly accessible folders"
    file:
      path: "/{{ folder_name }}"
      owner: root
      group: root
      mode: 0777
      state: directory
    with_items:
      - data
      - tmp2
    loop_control:
      loop_var: folder_name
    become: yes

  - name: "Create home bin folder"
    file:
      path: "/home/{{ admin_user }}/bin"
      owner: "{{ admin_user }}"
      group: "{{ admin_user_group }}"
      mode: 0755
      state: directory
      follow: yes

################################################################################
# Software Installations
################################################################################

  - name: "Install console tools"
    apt:
      name: "{{ console_tools }}"
      state: present
      update_cache: yes
    become: yes
