---
# tasks file for virtualbox

# https://www.virtualbox.org/wiki/Linux_Downloads

- name: "Select VirtualBox to install"
  include_tasks: "virtualbox_{{ my_ansible_distribution }}.yml"

- name: "Install VirtualBox extension pack"
  include_tasks: "virtualbox_extension_pack.yml"
