---
# tasks file for bash

- name: "Create symlink to .bash_functions"
  file:
    src: "{{ development_dir }}/dotfiles/bash/.bash_functions"
    dest: "/home/{{ ansible_user }}/.bash_functions"
    state: link

- name: "Create symlink to .bash_aliases"
  file:
    src: "{{ development_dir }}/dotfiles/bash/.bash_aliases"
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    state: link
