---

- name: "Install python-gpgme dependency for DropBox"
  apt:
    name:
      - python-gpgme
      - python3-gpgme
    state: present

- name: "Check if DropBox is installed"
  shell: dropbox status
  register: dropbox_status
  changed_when: False
  ignore_errors: yes

- name: "Download DropBox"
  get_url:
    url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb"
    dest: "/tmp/dropbox_2015.10.28_amd64.deb"
    mode: 0666
    owner: root
    group: root
  when: dropbox_status.stdout == ""

- name: "Install DropBox"
  apt:
    deb: "/tmp/dropbox_2015.10.28_amd64.deb"
  when: dropbox_status.stdout == ""
