---

software_pack:
  - aptitude
  - curl
  - git
  - htop
  - man
  - mdadm
  - mc
  - nano
  - p7zip
  - rar
  - sqlite3
  - sshfs
  - tasksel
  - tmux
  - tree
  - unar
  - unrar
  - unzip
  - wget
  - zip
