---
# HOST VARIABLES for joey_leap_42_3_desktop

# test host
ansible_host: 192.168.1.70

# production host
#ansible_host: 192.168.1.23

ansible_connection: ssh
ansible_user: joey

host_name: p6tdlxv2
time_zone: "America/Chicago"
