---
- name: "Add KeePassXC PPA for Ubuntu"
  apt_repository:
    repo: "ppa:phoerious/keepassxc"
    state: present
  become: yes

- name: "Install KeePassXC for Ubuntu"
  apt:
    name: keepassxc
    state: present
  become: yes
